import { SecurityPattern } from "../types.js";

export const securityPatterns: SecurityPattern[] = [
  {
    name: "XSS - dangerouslySetInnerHTML",
    pattern: /dangerouslySetInnerHTML/g,
    severity: "high",
    message: "Usage of dangerouslySetInnerHTML can lead to XSS attacks",
    recommendation: "Use DOMPurify for HTML sanitization or avoid innerHTML",
    explanation: "dangerouslySetInnerHTML in React allows direct HTML injection into the DOM without sanitization. If content comes from user input or untrusted sources, attackers can inject malicious scripts that will execute in the victim's browser, leading to cookie theft, session hijacking, or defacement.",
  },
  {
    name: "XSS - eval()",
    pattern: /\beval\s*\(/g,
    severity: "critical",
    message: "eval() can execute arbitrary code and is highly dangerous",
    recommendation: "Avoid eval(), use JSON.parse() or safer alternatives",
    explanation: "eval() executes strings as JavaScript code. If the string comes from user input or external sources, attackers can execute arbitrary code with application privileges. This is one of the most dangerous vulnerabilities as it can lead to remote code execution in the browser or server.",
  },
  {
    name: "Hardcoded Secrets",
    pattern: /(api[_-]?key|password|secret|token)\s*[:=]\s*['"][^'"]{8,}['"]/gi,
    severity: "critical",
    message: "API key or secret detected hardcoded in code",
    recommendation: "Use environment variables (.env) and do not commit secrets",
    explanation: "Secrets hardcoded in source code will be exposed in repositories (even if private), build artifacts, or when code is shared. Attackers who gain access to the code can use these secrets to access APIs, databases, or other services with application privileges.",
  },
  {
    name: "Insecure localStorage",
    pattern: /localStorage\.(setItem|getItem)/g,
    severity: "medium",
    message: "localStorage is not secure for sensitive data",
    recommendation: "Do not store tokens or sensitive data in localStorage, use httpOnly cookies",
    explanation: "localStorage can be accessed by JavaScript in the same origin, including scripts from XSS attacks. Data in localStorage is not automatically sent to the server like cookies, and does not have httpOnly protection. If the application is vulnerable to XSS, attackers can read all data from localStorage including authentication tokens.",
  },
  {
    name: "Missing Input Validation",
    pattern: /\b(req\.body|req\.query|req\.params)\.\w+(?!\s*&&|\s*\|\||\.)/g,
    severity: "high",
    message: "User input is not validated",
    recommendation: "Validate all input using libraries like zod or joi",
    explanation: "Unvalidated user input can lead to various attacks such as injection attacks (SQL, NoSQL, Command), type confusion, buffer overflow, or business logic bypass. Validation ensures data matches the expected format and is within safe ranges before processing.",
  },
  {
    name: "SQL Injection Risk",
    pattern: /(`|'|").*?\$\{.*?\}.*?\1.*?(SELECT|INSERT|UPDATE|DELETE)/gi,
    severity: "critical",
    message: "Potential SQL injection with string interpolation",
    recommendation: "Use parameterized queries or ORM like Prisma",
    explanation: "String interpolation in SQL queries allows attackers to inject SQL code that will be executed by the database. Attackers can read sensitive data, modify data, or even gain remote code execution on the database server. Parameterized queries separate data from query structure, preventing injection.",
  },
  {
    name: "Insecure Random",
    pattern: /Math\.random\(\)/g,
    severity: "medium",
    message: "Math.random() is not cryptographically secure",
    recommendation: "Use crypto.randomBytes() or crypto.getRandomValues() for security",
    explanation: "Math.random() uses a pseudo-random number generator that is predictable. For security purposes such as generating tokens, session IDs, or cryptographic keys, predictable values can be exploited. Attackers can guess or predict the generated values, compromising security mechanisms.",
  },
  {
    name: "CORS Misconfiguration",
    pattern: /cors\(\s*\{\s*origin\s*:\s*['"]?\*['"]?\s*\}\s*\)/g,
    severity: "high",
    message: "CORS configured to accept all origins (*)",
    recommendation: "Restrict CORS to trusted domains only",
    explanation: "CORS with origin '*' allows any website to make requests to the API from the browser. This enables attackers from malicious websites to make authenticated requests to the API if the user is logged in, causing CSRF attacks or unauthorized data access. CORS should be restricted to trusted domains only.",
  },
  {
    name: "Insecure HTTP",
    pattern: /['"]http:\/\//g,
    severity: "medium",
    message: "Using HTTP without encryption",
    recommendation: "Use HTTPS for all communications",
    explanation: "HTTP sends data in plain text without encryption. Attackers on the same network (public WiFi, man-in-the-middle) can intercept, read, and modify all communications including credentials, tokens, and sensitive data. HTTPS uses TLS/SSL to encrypt communications and verify server identity.",
  },
  {
    name: "Weak Crypto",
    pattern: /\b(md5|sha1)\b/gi,
    severity: "high",
    message: "Weak hashing algorithms (MD5/SHA1)",
    recommendation: "Use bcrypt, scrypt, or Argon2 for password hashing",
    explanation: "MD5 and SHA1 are hashing algorithms considered insecure due to vulnerability to collision attacks and being too fast for password hashing. Attackers can use rainbow tables or brute force to obtain passwords from hashes. For passwords, use algorithms specifically designed for this purpose like bcrypt which is slow and salt-based.",
  },
  {
    name: "Unsafe Redirect",
    pattern: /window\.location\s*=\s*\w+|router\.(push|replace)\(\s*\w+\s*\)/g,
    severity: "medium",
    message: "Open redirect vulnerability - redirect without validation",
    recommendation: "Validate redirect URLs against a whitelist of domains",
    explanation: "Unvalidated redirects allow attackers to redirect users to malicious websites. Attackers can use this for phishing (creating URLs that appear legitimate) or to bypass security controls. Users clicking redirect links will be sent to attacker websites that can steal credentials or install malware.",
  },
  {
    name: "Missing CSRF Protection",
    pattern: /<form(?![^>]*csrf)/gi,
    severity: "high",
    message: "Form without CSRF protection",
    recommendation: "Implement CSRF tokens for all form mutations",
    explanation: "CSRF (Cross-Site Request Forgery) allows attackers to make requests to the application on behalf of authenticated users. If a user visits a malicious website, attackers can create forms that submit to the target application, performing actions like changing passwords, transferring money, or deleting data without the user's knowledge. CSRF tokens verify that requests originate from the legitimate application.",
  },
  {
    name: "Exposed Server Info",
    pattern: /x-powered-by/gi,
    severity: "low",
    message: "X-Powered-By header can expose server information",
    recommendation: "Disable X-Powered-By header to avoid information disclosure",
    explanation: "The X-Powered-By header reveals the technology used by the application (e.g., Express, PHP version, etc.). This information helps attackers find vulnerabilities specific to that technology. Although not directly harmful, it reduces the attacker's effort in the reconnaissance phase. Security principle: minimize information disclosure.",
  },
  {
    name: "Missing Security Headers",
    pattern: /(Content-Security-Policy|X-Frame-Options|Strict-Transport-Security)/gi,
    severity: "medium",
    message: "Important security headers may not be configured",
    recommendation: "Implement CSP, X-Frame-Options, and HSTS headers",
    explanation: "Security headers provide an additional layer of protection in the browser. CSP (Content Security Policy) prevents XSS by restricting sources of executable scripts. X-Frame-Options prevents clickjacking by prohibiting embedding in iframes. HSTS forces browsers to use HTTPS. Without these headers, applications are more vulnerable to various client-side attacks.",
  },
];

